// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ClassMotion",
    platforms: [
        .iOS("19.0")
    ],
    products: [
        .iOSApplication(
            name: "ClassMotion",
            targets: ["AppModule"],
            bundleIdentifier: "com.Devansh.ClassMotion",
            teamIdentifier: "F5266U6VV9",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .movieReel),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "ClassMotion requires Camera permission to capture frames"),
                .microphone(purposeString: "ClassMotion requires Microphone permission to record audio"),
                .photoLibrary(purposeString: "ClassMotion requires permission to save exported videos to your Photo Library"),
                .photoLibraryAdd(purposeString: "ClassMotion requires permission to save exported videos to your Photo Library")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .unsafeFlags(["-Xfrontend", "-serialize-debugging-options"])
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)